// Code generated by "stringer -type=ErrCode -linecomment -output err_code_string.go"; DO NOT EDIT.

package ecode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InternalServerError-10500]
	_ = x[NotFound-10404]
	_ = x[MethodNotAllowed-10405]
	_ = x[BadRequest-10400]
	_ = x[TooManyRequests-10429]
	_ = x[Unauthorized-10401]
	_ = x[BadGateway-10502]
	_ = x[WaitQuery-10600]
	_ = x[ClientUUID-10611]
	_ = x[AppID-10612]
	_ = x[InvalidCaptcha-10613]
	_ = x[InvalidCiphertext-10614]
	_ = x[LoginFailed-10700]
	_ = x[UserNotExist-10701]
	_ = x[UsernameWrong-10702]
	_ = x[UserChipEmpty-10703]
	_ = x[UserChipNotEnough-10704]
	_ = x[DatabaseError-20100]
	_ = x[EventError-20101]
	_ = x[ModelNotFound-20102]
	_ = x[AliError-20200]
}

const (
	_ErrCode_name_0 = "BadRequestUnauthorized"
	_ErrCode_name_1 = "NotFoundMethodNotAllowed"
	_ErrCode_name_2 = "TooManyRequests"
	_ErrCode_name_3 = "InternalServerError"
	_ErrCode_name_4 = "BadGateway"
	_ErrCode_name_5 = "等待查询结果"
	_ErrCode_name_6 = "客户端标识错误应用标识错误验证码错误密文识别错误"
	_ErrCode_name_7 = "登录失败用户不存在账号错误代币额度为空代币余额不足"
	_ErrCode_name_8 = "数据操作失败事件处理失败ModelNotFound"
	_ErrCode_name_9 = "云服务错误"
)

var (
	_ErrCode_index_0 = [...]uint8{0, 10, 22}
	_ErrCode_index_1 = [...]uint8{0, 8, 24}
	_ErrCode_index_6 = [...]uint8{0, 21, 39, 54, 72}
	_ErrCode_index_7 = [...]uint8{0, 12, 27, 39, 57, 75}
	_ErrCode_index_8 = [...]uint8{0, 18, 36, 49}
)

func (i ErrCode) String() string {
	switch {
	case 10400 <= i && i <= 10401:
		i -= 10400
		return _ErrCode_name_0[_ErrCode_index_0[i]:_ErrCode_index_0[i+1]]
	case 10404 <= i && i <= 10405:
		i -= 10404
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	case i == 10429:
		return _ErrCode_name_2
	case i == 10500:
		return _ErrCode_name_3
	case i == 10502:
		return _ErrCode_name_4
	case i == 10600:
		return _ErrCode_name_5
	case 10611 <= i && i <= 10614:
		i -= 10611
		return _ErrCode_name_6[_ErrCode_index_6[i]:_ErrCode_index_6[i+1]]
	case 10700 <= i && i <= 10704:
		i -= 10700
		return _ErrCode_name_7[_ErrCode_index_7[i]:_ErrCode_index_7[i+1]]
	case 20100 <= i && i <= 20102:
		i -= 20100
		return _ErrCode_name_8[_ErrCode_index_8[i]:_ErrCode_index_8[i+1]]
	case i == 20200:
		return _ErrCode_name_9
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
