// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameArticleStatistic = "article_statistics"

// ArticleStatistic 文章内容
type ArticleStatistic struct {
	ArticleID  uint      `gorm:"column:article_id;primaryKey;comment:文章id" json:"article_id"` // 文章id
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
	CreatedAt  time.Time `gorm:"column:created_at;<-:create" json:"created_at"`
	Views      uint      `gorm:"column:views" json:"views"`
	Favourites uint      `gorm:"column:favourites" json:"favourites"`
}

// TableName ArticleStatistic's table name
func (*ArticleStatistic) TableName() string {
	return TableNameArticleStatistic
}
