// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameArticleTag = "article_tags"

// ArticleTag 文章标签
type ArticleTag struct {
	ID        uint           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;<-:create" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"-"`
	Name      string         `gorm:"column:name" json:"name"`
	Slug      string         `gorm:"column:slug" json:"slug"`
	Color     string         `gorm:"column:color" json:"color"`
}

// TableName ArticleTag's table name
func (*ArticleTag) TableName() string {
	return TableNameArticleTag
}
