// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"server/internal/core/model/accessor"

	"gorm.io/gorm"
)

const TableNameArticleCategory = "article_categories"

// ArticleCategory 文章分类
type ArticleCategory struct {
	ID          uint               `gorm:"column:id;primaryKey;autoIncrement:true;comment:文章分类id" json:"id"` // 文章分类id
	CreatedAt   time.Time          `gorm:"column:created_at;<-:create" json:"created_at"`
	UpdatedAt   time.Time          `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt     `gorm:"column:deleted_at" json:"-"`
	ParentID    uint               `gorm:"column:parent_id;comment:父级ID" json:"parent_id"`      // 父级ID
	Title       string             `gorm:"column:title;comment:文章分类标题" json:"title"`            // 文章分类标题
	ImageURL    accessor.StaticUrl `gorm:"column:image_url;comment:文章分类图片" json:"image_url"`    // 文章分类图片
	Keywords    string             `gorm:"column:keywords;comment:SEO关键词" json:"keywords"`      // SEO关键词
	Description string             `gorm:"column:description;comment:SEO描述" json:"description"` // SEO描述
	Sort        *int32             `gorm:"column:sort;default:255;comment:排序" json:"sort"`      // 排序
}

// TableName ArticleCategory's table name
func (*ArticleCategory) TableName() string {
	return TableNameArticleCategory
}
