// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameArticleTagRelate = "article_tag_relates"

// ArticleTagRelate 文章标签关联
type ArticleTagRelate struct {
	ArticleID uint `gorm:"column:article_id;primaryKey" json:"article_id"`
	TagID     uint `gorm:"column:tag_id;primaryKey" json:"tag_id"`
}

// TableName ArticleTagRelate's table name
func (*ArticleTagRelate) TableName() string {
	return TableNameArticleTagRelate
}
