// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameArticleContent = "article_contents"

// ArticleContent 文章内容
type ArticleContent struct {
	ArticleID uint      `gorm:"column:article_id;primaryKey;comment:文章id" json:"article_id"` // 文章id
	Content   string    `gorm:"column:content;comment:文章内容" json:"content"`                  // 文章内容
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ArticleContent's table name
func (*ArticleContent) TableName() string {
	return TableNameArticleContent
}
